# API Gateway Configuration for Development Environment

server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          # Global CORS configuration for development
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:3000"  # React web app
                  - "http://localhost:3001"  # Admin dashboard
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600

          # Default filters for development
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
            - AddRequestHeader=X-Gateway-Name, ChargeRoute-API-Gateway-Dev
            - AddRequestHeader=X-Request-Timestamp, #{T(java.time.Instant).now().toString()}
            - AddRequestHeader=X-Environment, development

          # Enable automatic route discovery from Eureka
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          # Custom route definitions
          routes:
            # User Management Service Routes
            - id: user-service-route
              uri: lb://user-management-service
              predicates:
                - Path=/api/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: user-service-cb
                    fallbackUri: forward:/fallback/users
                - AddRequestHeader=X-Service-Route, user-management

            # Charge Unit Management Service Routes  
            - id: charge-unit-service-route
              uri: lb://charge-unit-management-service
              predicates:
                - Path=/api/charge-units/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: charge-unit-service-cb
                    fallbackUri: forward:/fallback/charge-units
                - AddRequestHeader=X-Service-Route, charge-unit-management

            # Session Management Service Routes
            - id: session-service-route
              uri: lb://session-management-service
              predicates:
                - Path=/api/sessions/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: session-service-cb
                    fallbackUri: forward:/fallback/sessions
                - AddRequestHeader=X-Service-Route, session-management

            # Notification Management Service Routes
            - id: notification-service-route
              uri: lb://notification-management-service
              predicates:
                - Path=/api/notifications/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: notification-service-cb
                    fallbackUri: forward:/fallback/notifications
                - AddRequestHeader=X-Service-Route, notification-management

          # Development HTTP client settings - shorter timeouts
          httpclient:
            connect-timeout: 2000
            response-timeout: 5s

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.username:chargeroute}:${eureka.password:Admin123!}@${eureka.hostname:localhost}:${eureka.port:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10  # More frequent for dev
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # Development - faster heartbeat
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      zone: development
      version: 1.0.0-dev
      type: api-gateway

# Development logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.chargeroute.gateway: DEBUG
    reactor.netty.http.client: DEBUG